### ISSUE TITLE
Tracking for README Updates

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria-cli-go#144]
```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria-cli-go/issues/142
- [ ] https://github.com/astriaorg/astria-cli-go/issues/143
- [ ] https://github.com/astriaorg/astria-cli-go/issues/140
- [ ] https://github.com/astriaorg/astria-cli-go/issues/124
```
